######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 26 10:38:41 2007
######################################################################

qtopia_project(app)

depends(libraries/qtopiagfx)

TARGET = stars

#LIBS += mmx.o

# Input
SOURCES += test.cpp mmx.c
HEADERS += 
