#!/bin/sh
TOOLCHAIN=/opt/toolchains/armv5te-eabi
USE_TB=1
TB_CC_PREFIX=arm-linux-
TB_CC_VER=auto
TB_SYS=arm:eabi
export PKG_CONFIG_PREFIX=$TOOLCHAIN/arm-angstrom-linux-gnueabi
export PKG_CONFIG_PATH=$PKG_CONFIG_PREFIX/lib/pkgconfig
